"""Typed AI action service — run, guardrail, human-approve, mutate.

Runs are grounded in tenant-scoped context (cross-tenant retrieval is refused and
recorded as a guardrail violation). Output is generated by the deterministic stub
provider; authoritative mutations are applied *only* on human approval, and only
when guardrails pass (e.g. a citation-required action must be cited).
"""

from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ..config import get_settings
from ..models_ai_actions import (
    AiActionCitation,
    AiActionInput,
    AiActionOutput,
    AiActionReview,
    AiActionRun,
    AiApprovedMutation,
    AiGuardrailViolation,
)
from . import provider
from .registry import ActionDef, get_action


class AiActionError(ValueError):
    """Raised on an invalid action request (unknown action, bad entity type, …)."""


def _hash(obj: Any) -> str:
    return hashlib.sha256(
        json.dumps(obj, sort_keys=True, default=str).encode()
    ).hexdigest()


async def _audit(session: AsyncSession, **kw: Any) -> None:
    from ..api.audit import record_event  # noqa: PLC0415 — avoid import cycle

    await record_event(session, **kw)


async def _violation(
    session: AsyncSession, *, org_id: int | None, run_id: int | None, kind: str, detail: str
) -> None:
    session.add(
        AiGuardrailViolation(organization_id=org_id, run_id=run_id, kind=kind, detail=detail)
    )
    await _audit(
        session, actor="ai", action="update", entity_type="ai_guardrail",
        entity_id=str(run_id) if run_id else None,
        diff={"guardrail": kind, "detail": detail},
    )


# --- tenant-scoped context resolution ---------------------------------------


async def _resolve_context(
    session: AsyncSession, *, org_id: int | None, entity_type: str, entity_id: str
) -> dict[str, Any] | None:
    """Load grounding context for an entity, refusing cross-tenant access.

    Returns ``None`` when the entity does not exist. Raises :class:`PermissionError`
    when the entity exists but belongs to another tenant (guardrail).
    """
    owner_org, label, facts, sources = await _load_entity(session, entity_type, entity_id)
    if owner_org is None and label is None:
        return None
    if org_id is not None and owner_org is not None and owner_org != org_id:
        raise PermissionError("cross-tenant retrieval refused")
    return {
        "target_type": entity_type, "target_id": entity_id,
        "label": label, "facts": facts, "sources": sources, "owner_org": owner_org,
    }


async def _evidence_sources(
    session: AsyncSession, org_id: int | None, system_id: int | None, limit: int = 5
) -> list[dict[str, Any]]:
    from ..models_evidence import EvidenceObject  # noqa: PLC0415

    stmt = select(EvidenceObject)
    if system_id is not None:
        stmt = stmt.where(EvidenceObject.system_id == system_id)
    elif org_id is not None:
        stmt = stmt.where(EvidenceObject.organization_id == org_id)
    stmt = stmt.limit(limit)
    return [
        {"source_type": "evidence_object", "source_id": o.id, "label": o.title}
        for o in (await session.execute(stmt)).scalars().all()
    ]


async def _load_entity(  # noqa: PLR0911 — one branch per entity type
    session: AsyncSession, entity_type: str, entity_id: str
) -> tuple[int | None, str | None, dict[str, Any], list[dict[str, Any]]]:
    """Return ``(owner_org_id, label, facts, sources)`` for an entity, or Nones."""
    from ..models import (  # noqa: PLC0415
        POAM,
        ControlImplementation,
        Policy,
        Risk,
        System,
        Vendor,
    )

    try:
        eid = int(entity_id)
    except (TypeError, ValueError):
        eid = -1

    if entity_type == "system":
        s = await session.get(System, eid)
        if s is None:
            return None, None, {}, []
        srcs = await _evidence_sources(session, s.organization_id, s.id)
        facts = {"ato_status": s.ato_status, "baseline": s.baseline}
        return s.organization_id, s.name, facts, srcs
    if entity_type == "poam":
        p = await session.get(POAM, eid)
        if p is None:
            return None, None, {}, []
        sysm = await session.get(System, p.system_id)
        org = sysm.organization_id if sysm else None
        return org, p.title, {"severity": p.severity, "status": p.status}, [
            {"source_type": "poam", "source_id": p.id, "label": p.title}]
    if entity_type == "risk":
        r = await session.get(Risk, eid)
        if r is None:
            return None, None, {}, []
        sysm = await session.get(System, r.system_id) if r.system_id else None
        org = sysm.organization_id if sysm else None
        return org, r.title, {"status": r.status}, []
    if entity_type == "vendor":
        v = await session.get(Vendor, eid)
        if v is None:
            return None, None, {}, []
        return v.organization_id, v.name, {"risk_rating": v.risk_rating,
                                           "criticality": v.criticality}, []
    if entity_type == "control":
        impl = await session.get(ControlImplementation, eid)
        if impl is None:
            return None, None, {}, []
        sysm = await session.get(System, impl.system_id)
        org = sysm.organization_id if sysm else None
        srcs = await _evidence_sources(session, org, impl.system_id)
        return org, f"control impl {impl.id}", {
            "status": impl.status, "control_id": impl.control_id,
            "system_id": impl.system_id}, srcs
    if entity_type == "policy":
        pol = await session.get(Policy, eid)
        if pol is None:
            return None, None, {}, []
        return pol.organization_id, pol.name, {"status": pol.status}, []
    if entity_type == "evidence_object":
        from ..models_evidence import EvidenceObject  # noqa: PLC0415

        o = await session.get(EvidenceObject, eid)
        if o is None:
            return None, None, {}, []
        return o.organization_id, o.title, {"status": o.status, "source_type": o.source_type}, [
            {"source_type": "evidence_object", "source_id": o.id, "label": o.title}]
    if entity_type == "questionnaire_response":
        from ..models_tprm import QuestionnaireResponse, VendorQuestionnaire  # noqa: PLC0415

        resp = await session.get(QuestionnaireResponse, eid)
        if resp is None:
            return None, None, {}, []
        q = await session.get(VendorQuestionnaire, resp.questionnaire_id)
        org = q.organization_id if q else None
        srcs = await _evidence_sources(session, org, None)
        return org, resp.question_text[:80], {"answer": resp.answer}, srcs
    # Advisory-only entity types (regulatory_update, ksi, organization, ai_agent, connector):
    # no tenant-owned load wired yet → minimal context, no cross-tenant risk.
    return None, f"{entity_type} {entity_id}", {}, []


# --- run / approve / reject --------------------------------------------------


async def run_action(
    session: AsyncSession,
    *,
    action_key: str,
    entity_type: str,
    entity_id: str,
    org_id: int | None,
    actor: str | None,
) -> AiActionRun:
    action = get_action(action_key)
    if action is None:
        raise AiActionError(f"unknown action '{action_key}'")
    if entity_type not in action.input_entity_types:
        raise AiActionError(
            f"action '{action_key}' does not accept entity type '{entity_type}'"
        )

    settings = get_settings()
    run = AiActionRun(
        organization_id=org_id, action_key=action_key, entity_type=entity_type,
        entity_id=str(entity_id), actor=actor,
        provider=settings.ai_provider if settings.ai_enabled else "stub",
        status="pending_review" if action.requires_approval else "completed",
    )
    session.add(run)
    await session.flush()

    try:
        context = await _resolve_context(
            session, org_id=org_id, entity_type=entity_type, entity_id=entity_id
        )
    except PermissionError:
        run.status = "blocked"
        await _violation(
            session, org_id=org_id, run_id=run.id, kind="cross_tenant",
            detail=f"refused cross-tenant access to {entity_type} {entity_id}",
        )
        await session.flush()
        raise AiActionError("cross-tenant retrieval refused") from None
    if context is None:
        raise AiActionError(f"{entity_type} {entity_id} not found")

    result = provider.generate(action, context, provider=run.provider)
    citations = result["citations"]
    uncited = action.citation_required and not citations

    input_payload = {"entity_type": entity_type, "entity_id": entity_id, "facts": context["facts"]}
    run.input_hash = _hash(input_payload)
    run.output_hash = _hash(result["content"])
    run.summary = {"citation_count": len(citations), "uncited": uncited,
                   "mutation": action.allowed_mutation}
    session.add(AiActionInput(
        run_id=run.id, entity_type=entity_type, entity_id=str(entity_id),
        payload=input_payload, hash=run.input_hash))
    session.add(AiActionOutput(
        run_id=run.id, content=result["content"], uncited=uncited,
        payload=result["payload"], hash=run.output_hash))
    for c in citations:
        session.add(AiActionCitation(
            run_id=run.id, source_type=c["source_type"], source_id=c["source_id"],
            label=c.get("label")))

    if uncited and not settings.ai_allow_uncited_drafts:
        await _violation(
            session, org_id=org_id, run_id=run.id, kind="missing_citation",
            detail=f"citation-required action '{action_key}' produced no citations",
        )
    await _audit(
        session, actor=actor or "ai", action="create", entity_type="ai_action",
        entity_id=str(run.id),
        diff={"action": action_key, "target": f"{entity_type}:{entity_id}",
              "status": run.status, "input_hash": run.input_hash, "output_hash": run.output_hash},
    )
    await session.flush()
    return run


async def _apply_mutation(
    session: AsyncSession, run: AiActionRun, action: ActionDef, output: AiActionOutput
) -> dict[str, Any]:
    """Apply the action's declared authoritative mutation. Returns a record dict."""
    from ..models import POAM, Task  # noqa: PLC0415

    payload = output.payload or {}
    if action.allowed_mutation == "set_poam_remediation":
        poam = await session.get(POAM, int(run.entity_id or "0"))
        if poam is not None:
            poam.remediation_plan = payload.get("remediation_plan") or output.content
            return {"mutation_type": "set_poam_remediation", "target_type": "poam",
                    "target_id": run.entity_id}
    elif action.allowed_mutation == "create_task":
        t = payload.get("task", {})
        task = Task(
            organization_id=run.organization_id, title=t.get("title", "AI-suggested task"),
            description=output.content, kind="ai_action", priority=t.get("priority", "medium"),
            status="open", source="ai", entity_type=run.entity_type, entity_id=str(run.entity_id),
        )
        session.add(task)
        await session.flush()
        return {"mutation_type": "create_task", "target_type": "task", "target_id": str(task.id)}
    elif action.allowed_mutation == "create_control_test":
        from ..models_grc import ControlTest  # noqa: PLC0415

        ct = payload.get("control_test", {})
        test = ControlTest(
            organization_id=run.organization_id, control_id=str(ct.get("control_id") or ""),
            name=ct.get("name", "AI-proposed test"), method=ct.get("method", "manual"),
            frequency=ct.get("frequency"),
        )
        session.add(test)
        await session.flush()
        return {"mutation_type": "create_control_test", "target_type": "control_test",
                "target_id": str(test.id)}
    elif action.allowed_mutation == "set_response_suggestion":
        from ..models_tprm import QuestionnaireResponse  # noqa: PLC0415

        resp = await session.get(QuestionnaireResponse, int(run.entity_id or "0"))
        if resp is not None:
            resp.detail = f"[AI suggestion] {payload.get('suggested_answer', '')}: {output.content}"
            return {"mutation_type": "set_response_suggestion",
                    "target_type": "questionnaire_response", "target_id": run.entity_id}
    return {"mutation_type": action.allowed_mutation or "none", "target_type": None,
            "target_id": None}


async def approve_run(
    session: AsyncSession, run: AiActionRun, *, reviewer: str | None
) -> AiActionRun:
    """Approve a run and apply its declared mutation, subject to guardrails."""
    if run.status not in ("pending_review", "draft"):
        raise AiActionError(f"run is not awaiting review (status={run.status})")
    action = get_action(run.action_key)
    if action is None:
        raise AiActionError("action definition no longer exists")

    output = (
        await session.execute(select(AiActionOutput).where(AiActionOutput.run_id == run.id))
    ).scalars().first()

    # Guardrail: a citation-required action must be cited before it can mutate.
    if action.citation_required and output is not None and output.uncited:
        run.status = "blocked"
        await _violation(
            session, org_id=run.organization_id, run_id=run.id, kind="unapproved_mutation",
            detail="blocked approval: citation-required action is uncited",
        )
        await session.flush()
        raise AiActionError("cannot approve an uncited citation-required action")

    # Guardrail: no package build without existing provenance.
    if "no_provenance" in action.guardrails and not await _has_provenance(session, run):
        run.status = "blocked"
        await _violation(
            session, org_id=run.organization_id, run_id=run.id, kind="no_provenance",
            detail="blocked: build_trust_package requires an existing authorization package",
        )
        await session.flush()
        raise AiActionError("no authorization package provenance for this system")

    mutation = {"mutation_type": "none", "target_type": None, "target_id": None}
    if action.allowed_mutation and output is not None:
        mutation = await _apply_mutation(session, run, action, output)
        run.mutation_applied = mutation["target_id"] is not None
        if run.mutation_applied:
            session.add(AiApprovedMutation(
                organization_id=run.organization_id, run_id=run.id,
                mutation_type=mutation["mutation_type"], target_type=mutation["target_type"],
                target_id=mutation["target_id"], approved_by=reviewer, payload=output.payload))

    run.status = "approved"
    run.reviewer = reviewer
    run.disposition = "approved"
    run.decided_at = datetime.now(UTC)
    session.add(AiActionReview(run_id=run.id, reviewer=reviewer, decision="approved"))
    await _audit(
        session, actor=reviewer or "reviewer", action="update", entity_type="ai_action",
        entity_id=str(run.id),
        diff={"disposition": "approved", "mutation": mutation, "action": run.action_key},
    )
    await session.flush()
    return run


async def _has_provenance(session: AsyncSession, run: AiActionRun) -> bool:
    try:
        from ..models_packages import AuthorizationPackage  # noqa: PLC0415

        if run.entity_type != "system":
            return True
        pkg = (
            await session.execute(
                select(AuthorizationPackage).where(
                    AuthorizationPackage.system_id == int(run.entity_id or "0")
                ).limit(1)
            )
        ).scalars().first()
        return pkg is not None
    except Exception:
        return True


async def reject_run(
    session: AsyncSession, run: AiActionRun, *, reviewer: str | None, note: str | None = None
) -> AiActionRun:
    """Reject a run — the full record is preserved for audit."""
    if run.status not in ("pending_review", "draft", "blocked"):
        raise AiActionError(f"run is not awaiting review (status={run.status})")
    run.status = "rejected"
    run.reviewer = reviewer
    run.disposition = "rejected"
    run.decided_at = datetime.now(UTC)
    session.add(AiActionReview(run_id=run.id, reviewer=reviewer, decision="rejected", note=note))
    await _audit(
        session, actor=reviewer or "reviewer", action="update", entity_type="ai_action",
        entity_id=str(run.id), diff={"disposition": "rejected", "note": note},
    )
    await session.flush()
    return run
